DATA:
  DATASET: csiq
  BATCH_SIZE: 48
  PATCH_NUM: 10
  TEST_PATCH_NUM: 15
  CROP_SIZE: (224,224)
SET:
  COUNT: 30
MODEL:
  TYPE: dformer
  NAME: cross-to-csiq
  DROP_PATH_RATE: 0.0
  DINET:
    DIMS: [96, 192, 288, 576]
    MLP_RATIOS: [8, 8, 4, 4]
    DEPTHS: [3, 3, 12, 2]
    NUM_HEADS: [1, 2, 4, 8]
    WINDOWS: [0, 7, 7, 7]
    PRETRAINED: False
    CROSS_VALID: True
    CROSS_MODEL_PATH: results/ablation-live/dinet_live_save_ckpts/0/ckpt_epoch_6.pth
TRAIN:
  EPOCHS: 9
  WARMUP_EPOCHS: 3
  WEIGHT_DECAY: 0.05
  BASE_LR: 2.0e-4
  WARMUP_LR: 2.0e-7
  MIN_LR: 2.0e-7
  LR_SCHEDULER:
    NAME: step
    DECAY_EPOCHS: 3
DISABLE_SAVE: True
