# Equal BS: 152
DATA:
  DATASET: koniq
  BATCH_SIZE: 76
  PATCH_NUM: 3
  TEST_PATCH_NUM: 15
  CROP_SIZE: (384,384)
SET:
  COUNT: 10073
MODEL:
  TYPE: deit_large
  NAME: small_size
  DROP_PATH_RATE: 0.0
  VIT:
    INPUT_SIZE : 384
    MODEL_SIZE : small
    PATCH_SIZE : 16
    EMBED_DIM : 384
    DEPTH : 12
    NUM_HEADS : 6
    MLP_RATIO : 4
    QKV_BIAS : True
    # # Download the pretrained weights and input the path here
    PRETRAINED: False
    CROSS_VALID: True
    CROSS_MODEL_PATH: /media/hdd1/fubohan/results/cross/full_livec_weight/7/ckpt_epoch_8.pth
TRAIN:
  EPOCHS: 9
  WARMUP_EPOCHS: 3
  WEIGHT_DECAY: 0.05
  BASE_LR: 2.0e-4
  WARMUP_LR: 2.0e-7
  MIN_LR: 2.0e-7
  LR_SCHEDULER:
    NAME: step
    DECAY_EPOCHS: 3
DISABLE_SAVE: True
