DATA:
  DATASET: koniq
  BATCH_SIZE: 128
  PATCH_NUM: 10
  CROP_SIZE: (224,224)
SET:
  COUNT: 10073
MODEL:
  TYPE: star
  NAME: dev-small
  DROP_PATH_RATE: 0.0
  STAR:
    DEPTHS: [3, 3, 12, 5]
    DIMS: 32
    MLP_RATIO: 4
    # Download the pretrained weights and input the path here
    PRETRAINED: True
    PRETRAINED_MODEL_PATH: /home/fubohan/Code/DIQA-dev/checkpoint/starnet_s4.pth
TRAIN:
  EPOCHS: 9
  WARMUP_EPOCHS: 3
  WEIGHT_DECAY: 0.05
  BASE_LR: 2.0e-4
  WARMUP_LR: 2.0e-7
  MIN_LR: 2.0e-7
  LR_SCHEDULER:
    NAME: step
    DECAY_EPOCHS: 3
DISABLE_SAVE: True
