DATA:
  DATASET: koniq
  # BATCH_SIZE: 39  # 4卡
  BATCH_SIZE: 52  # 3卡
  PATCH_NUM: 3
  TEST_PATCH_NUM: 15
  CROP_SIZE: (384,384)
SET:
  COUNT: 10073
MODEL:
  TYPE: mamba
  NAME: dev-small
  DROP_PATH_RATE: 0.0
  MAMBA:
    DEPTHS: [3, 3, 10, 5]
    NUM_HEADS: [2, 4, 8, 16]
    WINDOW_SIZE: [8, 8, 14, 7]
    DIM: 128
    IN_DIM: 64
    MLP_RATIO: 4
    RESOLUTION: 224
    DROP_PATH: 0.
    LAYER_SCALE: 1e-5
    # Download the pretrained weights and input the path here
    PRETRAINED: True
    PRETRAINED_MODEL_PATH: /home/fubohan/Code/DIQA-dev/checkpoint/mambavision_base_1k.pth
TRAIN:
  EPOCHS: 9
  WARMUP_EPOCHS: 3
  WEIGHT_DECAY: 0.05
  BASE_LR: 2.0e-4
  WARMUP_LR: 2.0e-7
  MIN_LR: 2.0e-7
  LR_SCHEDULER:
    NAME: step
    DECAY_EPOCHS: 3
DISABLE_SAVE: True
