# For livefv, we recommend use 8 GPUs for reproduction
DATA:
  DATASET: livefb
  BATCH_SIZE: 38
  PATCH_NUM: 1
  TEST_PATCH_NUM: 1
  CROP_SIZE: (224,224)
SET:
  COUNT: 39810
MODEL:
  TYPE: dformer
  NAME: livefb
  DROP_PATH_RATE: 0.0
  DINET:
    DIMS: [96, 192, 288, 576]
    MLP_RATIOS: [8, 8, 4, 4]
    DEPTHS: [3, 3, 12, 2]
    NUM_HEADS: [1, 2, 4, 8]
    WINDOWS: [0, 7, 7, 7]
    # Download the pretrained weights and input the path here
    PRETRAINED: True
    PRETRAINED_MODEL_PATH: checkpoints/DFormer_Large.pth
TRAIN:
  EPOCHS: 9
  WARMUP_EPOCHS: 3
  WEIGHT_DECAY: 0.05
  BASE_LR: 2.0e-4
  WARMUP_LR: 2.0e-7
  MIN_LR: 2.0e-7
  LR_SCHEDULER:
    NAME: step
    DECAY_EPOCHS: 3
DISABLE_SAVE: True
