DATA:
  DATASET: spaq
  BATCH_SIZE: 22 # equal 64
  PATCH_NUM: 2
  TEST_PATCH_NUM: 15
  CROP_SIZE: (384,384)
SET:
  COUNT: 11125
MODEL:
  TYPE: deit_large
  NAME: kadid_test
  DROP_PATH_RATE: 0.0
  VIT:
    INPUT_SIZE : 384
    MODEL_SIZE : base
    PATCH_SIZE : 16
    EMBED_DIM : 384
    DEPTH : 12
    NUM_HEADS : 6
    MLP_RATIO : 4
    QKV_BIAS : True
    # # Download the pretrained weights and input the path here
    PRETRAINED: True
    PRETRAINED_MODEL_PATH: /home/fubohan/Code/DIQA/checkpoint/deit_3_small_384_21k.pth
TRAIN:
  EPOCHS: 9
  WARMUP_EPOCHS: 3
  WEIGHT_DECAY: 0.05
  BASE_LR: 2.0e-4
  WARMUP_LR: 2.0e-7
  MIN_LR: 2.0e-7
  # ACCUMULATION_STEPS: 2
  LR_SCHEDULER:
    NAME: step
    DECAY_EPOCHS: 3
DISABLE_SAVE: True
